unbind C-b
set -g prefix `
bind-key ` send-prefix

set -g mouse on
bind Space last-window
setw -g mode-keys vi
set -sg escape-time 0
set-option -g history-limit 5000

bind-key -n C-a send-keys C-a
bind-key -n C-e send-keys C-e

bind r source-file ~/.config/tmux/tmux.conf 

# set -g status-position bottom
# set -g status-left ''
# set -g status-right-length 50
# set -g status-left-length 20
setw -g mode-keys vi

# setw -g window-status-current-format ' #I#[fg=colour250]:#[fg=colour255]#W#[fg=colour50]#F '
# setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '

##### Status Bar #####
set -g status-position bottom
set -g status-interval 2
set -g status-justify centre
set -g status-style "bg=#282828,fg=#a89984"
set -g status-left-length 30
set -g status-right-length 60

##### Left #####
set -g status-left "#[fg=#928374,bg=#282828,bold]#S "

##### Windows #####
setw -g window-status-format "#I#[fg=#665c54]:#W"
setw -g window-status-current-format "#[fg=#ebdbb2,bold]#W"

# setw -g window-status-separator "  •  "
setw -g window-status-separator "    "

##### Right #####
set -g status-right "#[fg=#665c54]%H:%M"

##### Borders #####
set -g pane-border-style "fg=#3c3836"
set -g pane-active-border-style "fg=#d79921"

##### Messages #####
set -g message-style "fg=#ebdbb2,bg=#3c3836"
set -g mode-style "fg=#282828,bg=#fabd2f"

##### Prefix indicator #####
set -g @prefix_highlight_fg "#282828"
set -g @prefix_highlight_bg "#fe8019"
